### PR TITLE
COPYTO fix casting

### PR DESCRIPTION
**Pull request by densmirn**

### CODE REVIEW

**Comment by Alexander-Makaryev** [comment]
Yesterday we discussed the PR
https://github.com/IntelPython/dpnp/pull/584
I suggested to use existing macros instead of writing new code.
To demonstrate alternative solution I created a separate PR
https://github.com/IntelPython/dpnp/pull/590
BTW I found and fixed a bug in macros MACRO_1ARG_2TYPES_OP, maybe this is the reasone why it is not used here.
Please, look at alternative variant and choose the best one.
Feel free to use my branch/PR for modifications.

**Comment by densmirn** [comment]
> Yesterday we discussed the PR
> #584
> I suggested to use existing macros instead of writing new code.
> To demonstrate alternative solution I created a separate PR
> #590
> BTW I found and fixed a bug in macros MACRO_1ARG_2TYPES_OP, maybe this is the reason why it is not used here.
> Please, look at alternative variant and choose the best one.
> Feel free to use my branch/PR for modifications.

Yes, it was a reason why I didn't use the macros. Let me use the macros in the PR. I will reuse you branch here.

**Comment by densmirn** [comment]
> Yesterday we discussed the PR
> #584
> I suggested to use existing macros instead of writing new code.
> To demonstrate alternative solution I created a separate PR
> #590
> BTW I found and fixed a bug in macros MACRO_1ARG_2TYPES_OP, maybe this is the reason why it is not used here.
> Please, look at alternative variant and choose the best one.
> Feel free to use my branch/PR for modifications.

Another reason why I didn't use the macros is different signature of the macros and the separate kernel `f(src, dst) vs f(dst, src)`.

**Comment by shssf** [comment]
We don't have to use macro.
Macro is just for comfort of the programmer.
We can implement this function standalone.

**Review by shssf — APPROVED** [review]

**Pull request merged**
