### PR TITLE
BUG: fix asanyarray fallback + disabled tests

### PR DESCRIPTION
**Pull request by samir-nasibli**
## Description
* removed dpnp error raise, fallback when order is not c contiguous
 DPNP error: in function asanyarray() paramenter 'order' expected `C`, but 'None' provided -> 'int' object has no attribute 'c_contiguous'
* disabled tests for ['int' object has no attribute 'c_contiguous']. See `Reproduce dpctl usm_array flags` below
```bash
tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_asanyarray_with_order
tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_asarray_from_numpy
tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_asarray_with_order
```

## Test
FAILED tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_asanyarray_with_order
```bash
tests/third_party/cupy/creation_tests/test_from_data.py:365: in test_asanyarray_with_order
    b = xp.asanyarray(a, order=order)
dpnp/dpnp_iface_arraycreation.py:252: in asanyarray
    checker_throw_value_error("asanyarray", "order", order, 'C')
dpnp/dpnp_utils/dpnp_algo_utils.pyx:189: in dpnp.dpnp_utils.dpnp_algo_utils.checker_throw_value_error
    cpdef checker_throw_value_error(function_name, param_name, param, expected):
dpnp/dpnp_utils/dpnp_algo_utils.pyx:194: in dpnp.dpnp_utils.dpnp_algo_utils.checker_throw_value_error
    raise ValueError(err_msg)
E   AssertionError: Only cupy raises error
E   
E     File "/localdisk/work/snasibli/dpnp_work/tmp2/dpnp/tests/third_party/cupy/testing/helper.py", line 30, in _call_func
E       result = impl(self, *args, **kw)
E     File "/localdisk/work/snasibli/dpnp_work/tmp2/dpnp/tests/third_party/cupy/creation_tests/test_from_data.py", line 365, in test_asanyarray_with_order
E       b = xp.asanyarray(a, order=order)
E     File "/localdisk/work/snasibli/dpnp_work/tmp2/dpnp/dpnp/dpnp_iface_arraycreation.py", line 252, in asanyarray
E       checker_throw_value_error("asanyarray", "order", order, 'C')
E     File "dpnp/dpnp_utils/dpnp_algo_utils.pyx", line 189, in dpnp.dpnp_utils.dpnp_algo_utils.checker_throw_value_error
E       cpdef checker_throw_value_error(function_name, param_name, param, expected):
E     File "dpnp/dpnp_utils/dpnp_algo_utils.pyx", line 194, in dpnp.dpnp_utils.dpnp_algo_utils.checker_throw_value_error
E       raise ValueError(err_msg)
E   DPNP error: in function asanyarray() paramenter 'order' expected `C`, but 'None' provided
```

Now there are another fail on test:
```bash
tests/third_party/cupy/creation_tests/test_from_data.py:369: in test_asanyarray_with_order
    assert b.flags.c_contiguous
E   AssertionError: Only cupy raises error
E
E     File "/localdisk/work/snasibli/dpnp_work/tmp2/dpnp/tests/third_party/cupy/testing/helper.py", line 30, in _call_func
E       result = impl(self, *args, **kw)
E     File "/localdisk/work/snasibli/dpnp_work/tmp2/dpnp/tests/third_party/cupy/creation_tests/test_from_data.py", line 369, in test_asanyarray_with_order
E       assert b.flags.c_contiguous
E   'int' object has no attribute 'c_contiguous'
```

This fail happens due dpctl usm_ndarray, that have a bug for `flags`.
## Reproduce dpctl usm_array flags
```python
>>> a = dpnp.asanyarray([12,34], order='C')
>>> a = dpnp.asanyarray([12,34], order='K')
>>> a
<dpctl.tensor._usmarray.usm_ndarray object at 0x7fdec18e4130>
>>> a.flags
1
>>> import numpy
>>> b = numpy.asanyarray([12,34], order='K')
>>> b.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```
'int' object has no attribute 'c_contiguous'

### CODE REVIEW

**Comment by samir-nasibli** [comment]
@Alexander-Makaryev I have disabled tests that fail due dpctl bug (see. Reproduce dpctl usm_array flags on description). If it is necessary I will create issue for this on dpctl repo.

**Comment by Alexander-Makaryev** [comment]
@oleksandr-pavlyk Could you lease look at it? Is Samir right?

**Comment by oleksandr-pavlyk** [comment]
`usm_ndarray.flags` indeed gives an integer, encoded using bits. Bit 0 is set if array is C-contiguous, bit 1 if F-contiguous and bit 2 if writeable.

**Comment by samir-nasibli** [comment]
@Alexander-Makaryev @oleksandr-pavlyk  `usm_ndarray` interface is not compatible with these `third-party/cupy` test cases. `numpy.ndarray` for `flags` method returns `numpy.flagsobj`, while `usm_ndarray` returns `int` val for `flags` method. third-party/cupy` test cases require `flagsobj` object. We shouldn't change third-party tests, we can only disable tests, what has already been done in this PR.

**Comment by Alexander-Makaryev** [comment]
@samir-nasibli Could you please remove the skipping of tests from this PR?

**Pull request merged**
