### PR TITLE
ENH: added `random.binomial`

### PR DESCRIPTION
**Pull request by samir-nasibli**
## Description
 binomial(n, p[, size]) Draw samples from a binomial distribution.

## TODO:
* Adding supported devices into `Note`: is it needed??

## Reproduce
```python
>>> n, p = 10, .5  # number of trials, probability of each trial
>>> np.mean(dpnp.random.binomial(n, p, size=10**6))
4.996301
>>> np.var(dpnp.random.binomial(n, p, size=10**6))
2.499601238400478
>>> np.mean(np.random.binomial(n, p, size=10**6))
4.999603
>>> np.var(np.random.binomial(n, p, size=10**6))
2.493133874279
```

## Checklist

- [x] Docstrings for all functions
- [ ] Gallery example in ./doc/examples (new features only)
- [X] Unit tests:
- [X] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

### CODE REVIEW

**Review by shssf — APPROVED** [review]

**Comment by oleksandr-pavlyk** [comment]
Unexpected:

```
In [18]: np.unique(np.asarray(dpnp.random.binomial(11, 1.0, size=100)))
Out[18]: array([0], dtype=int32)

In [19]: np.unique(np.asarray(np.random.binomial(11, 1.0, size=100)))
Out[19]: array([11])
```

**Comment by samir-nasibli** [comment]
> Unexpected:
> 
> ```
> In [18]: np.unique(np.asarray(dpnp.random.binomial(11, 1.0, size=100)))
> Out[18]: array([0], dtype=int32)
> 
> In [19]: np.unique(np.asarray(np.random.binomial(11, 1.0, size=100)))
> Out[19]: array([11])
> ```
Thank you for the great report. I have fixed this bug.
See:
```python
>>> np.unique(np.asarray(dpnp.random.binomial(11, 1.0, size=100)))
array([11], dtype=int32)
>>> np.unique(np.asarray(np.random.binomial(11, 1.0, size=100)))
array([11])

```

**Comment by shssf** [comment]
@samir-nasibli Please notify me when this PR can be merged

**Review by oleksandr-pavlyk — APPROVED** [review]
LGTM. 

To handle run-time errors, and not cause the crash, the call to C++ function doing the sampling must be wrapped in `try{ .. } catch (...) { }` and caught errors must be translated to Python exceptions. 

It seems like this must be done for every distribution.

**Pull request merged**
