### PR TITLE
SYCL USM iterator with axis support plus few tests

### PR DESCRIPTION
**Pull request by shssf**
To continue work started by @Alexander-Makaryev 

this is initial code. a lot of things need to be added.
- iterator tests (std::vector::iterator like)
- algorithm tests with corner cases check
- algorithms check with error handling
- tests with diffrent types
and much more

will be addressed by next PRs. This PR is complete.

### CODE REVIEW

**Comment by samir-nasibli** [comment]
@shssf I have checked tests - all passed OK. Lets merge #552 and #559 for getting green CI results for your features tests.

**Review by samir-nasibli — DISMISSED** [review]
@shssf Looks good to me. We can merge it on master, and add other features for improvement on smaller PRs.

**Review by samir-nasibli — DISMISSED** [review]
Lets have this features on master 👍

**Review by Alexander-Makaryev — APPROVED** [review]
👍

**Pull request merged**
