### PR TITLE
Add missing dtype aliases

### PR DESCRIPTION
**Pull request by antonwolfy**
The list of missing aliases on numpy types are ported to dpnp:
- cdouble
- complex_
- complexfloating
- cfloat
- csingle
- double
- float_
- floating
- inexact
- int_
- intc
- number
- object_
- signedinteger
- single
- singlecomplex

The flowing type-related functions are added to dpnp:
 - issubdtype
 - issubsctype

The following constants are borrowed from numpy:
 - e
 - euler_gamma
 - Inf
 - inf
 - Infinity
 - infty
 - NAN
 - NaN
 - NINF
 - NZERO
 - pi
 - PINF
 - PZERO

This PR is intended to resolve issue #1307.

- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to issue with a reproducer?
- [x] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?

### CODE REVIEW

**Review by vlad-perevezentsev — APPROVED** [review]
LGTM!

**Comment by oleksandr-pavlyk** [comment]
I would suggest to remove `dpnp.object_` since `dnp` does not support this data type.

**Review by oleksandr-pavlyk — CHANGES_REQUESTED** [review]
I do not understand why we export and `dpnp.longcomplex` (a.k.a `np.complex256`) as we do not export `dpnp.longdouble` (a.k.a. `np.float128`) and we do not support this data type. 

We also do no support `np.void`, so I suggest we remove `dpnp.void` too.

**Comment by antonwolfy** [comment]
> I do not understand why we export and `dpnp.longcomplex` (a.k.a `np.complex256`) as we do not export `dpnp.longdouble` (a.k.a. `np.float128`) and we do not support this data type.
> 
> We also do no support `np.void`, so I suggest we remove `dpnp.void` too.

Ok, agree.
What do you think to add constants like `dpnp.pi`, `dpnp.inf` and other ones from numpy? (they are also available in cupy as I can see)

**Comment by oleksandr-pavlyk** [comment]
`pi`, `e`, `nan`, `inf`, `newaxis` are mandated by array API.

**Review by oleksandr-pavlyk — APPROVED** [review]

**Pull request merged**
