### PR TITLE
Add triggers to CI

### PR DESCRIPTION
**Pull request by 1e-to**
Add triggers to CI: upload packages on setting tags and push to releases branches

### CODE REVIEW

**Comment by Alexander-Makaryev** [comment]
@1e-to @PokhodenkoSA Is this PR actual?

**Comment by PokhodenkoSA** [comment]
> Is this PR actual?

I think yes. But @1e-to will have to review it again.

**Comment by Alexander-Makaryev** [comment]
@1e-to @PokhodenkoSA Is this PR actual?

**Comment by PokhodenkoSA** [comment]
@1e-to, please, update it.

**Comment by antonwolfy** [comment]
The PR is obsolete, no `release` branch is going to be added.

**Pull request closed without merging**
