### PR TITLE
Use Python 3.9 [public CI]

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
- [x] Update GitHub CI for building development package
- [x] Update conda recipe
- [x] Dependencies
  - [x] https://github.com/IntelPython/dpctl/pull/599
- [x] Install oneAPI 2021.3 via APT
 
Closes #984.

### CODE REVIEW

**Review by Alexander-Makaryev — APPROVED** [review]
LGTM

**Comment by PokhodenkoSA** [comment]
oneAPI 2021.4 installed from apt packages, but also oneAPI 2021.3 packages installed in conda build environment. I think there is conflict. I will try to remove oneAPI from system and use only conda packages.

**Comment by Alexander-Makaryev** [comment]
> oneAPI 2021.4 installed from apt packages, but also oneAPI 2021.3 packages installed in conda build environment. I think there is conflict. I will try to remove oneAPI from system and use only conda packages.

The root cause is in new version of oneDPL/PSTL (one of components in oneAPI), it has incompatible changes.
This component is not present yet as a Python package, that is why using only packages is impossible.

**Comment by Alexander-Makaryev** [comment]
Downgrading of oneDPL/PSTL to previous version (made by downgrading of oneAPI) is a temporary way of dealing with a problem, it should be fixed in future. Created issue https://github.com/IntelPython/dpnp/issues/986

**Pull request merged**
